[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "sunny fresh link write tonight stable robust job rabbit bone rent bunker eight zone regret mule merry sketch traffic vital inner noise display zone"
