[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "soon empower before grocery next much tool tattoo praise range tattoo monitor fuel busy spring output trigger dry crowd patch soon flag spread symbol"